# Generated by Django 3.2.2 on 2021-05-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Título')),
                ('isbn', models.CharField(max_length=64, verbose_name='ISBN')),
                ('published_by', models.CharField(max_length=128, verbose_name='Editora')),
                ('book_edition', models.CharField(max_length=128, verbose_name='Edição')),
                ('pages', models.IntegerField(verbose_name='Número de páginas')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('author', models.ManyToManyField(to='books_api.Author', verbose_name='Autor(es)')),
            ],
        ),
    ]
