# Generated by Django 3.2.2 on 2021-05-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nome'),
        ),
    ]
